server:
  # 应用服务web访问端口
  port: 7100
  max-http-header-size: 4048576
  servlet:
    context-path: "/model-designer"
spring:
  application:
    name: model-designer-service
  cloud:
    nacos:
      discovery:
        # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos服务器主机和端口
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.oscar.Driver
    url: jdbc:oscar://10.200.72.155:2003/OSRDB
    username: MODEL_DESIGNER
    password: oa_123
  redis:
    database: 0
    host: 127.0.0.1
    password: Aqkk25571a?!!
    port: 6379
  servlet:
    multipart:
      #文件大小
      max-file-size: 200MB
      max-request-size: 800MB
feign:
  hystrix:
    enabled: true
  client:
    config:
      # 指定service-id,default默认所有服务；
      default:
        # 网络连接超时时间
        connectionTimeout: 20000
        # 读超时时间
        readTimeout: 20000
  httpclient:
    connection-timeout: 20000
    connection-timer-repeat: 30000
ribbon:
  eager-load:
    #开启饥饿加载模式
    enabled: true
    #配置客户端列表
    clients: bsp, bpm, cform
  #连接超时时间，单位为毫秒
  ConnectTimeout: 20000
  #读超时时间，单位为毫秒
  ReadTimeout: 20000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # Hystrix超时时间
            timeoutInMilliseconds: 100000
logging:
  level:
    # 调用bsp,bpm,cform增加feign日志打印
    com.inspur.modeldesigner.manage.feignservice.**: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# feign客户端定义
feignClient:
  bpm: bpm
  bsp: bsp
  cform: cform
  edoc-service: edoc-service
  system-service: system-service

# 导出文件签名加盐
exportFile:
  salt: 加盐齁咸！
